### ISSUE TITLE
Actions should be required to return the same shaped state

### ISSUE THREAD

**Issue by kalvinpearce** [kalvinpearce/react-microdux#4]
An action can modify the root shape of the state when it shouldn't be allowed to eg:
```ts
const action: Action<State, undefined> = (state, payload) => ({
    ...state,
    newThing: 'not part of the state' // this should not be allowed
)};
```

**Comment by JamesYFC** [comment]
https://github.com/microsoft/TypeScript/issues/241

**Comment by kalvinpearce** [comment]
I guess since its a fairly old issue it likely won't be fixed any time soon. However I think it should be okay as even if you return something that isn't part of the initial state, you can't access it from the returned `.state` anyway
